
# Generated by Django 3.1.2 on 2020-11-02 02:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('team_name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('profile_pic', models.BinaryField()),
                ('about_me', models.CharField(max_length=300)),
                ('skills', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('counter', models.IntegerField(default=5)),
                ('poc_email', models.CharField(max_length=100)),
                ('start_timeline', models.DateTimeField()),
                ('end_timeline', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('poc_name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='backend.person')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=1000)),
                ('team_leader', models.CharField(max_length=100)),
                ('team_info', models.CharField(max_length=100000)),
                ('team_progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('team_picture', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('counter', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('poc_email', models.CharField(max_length=100)),
                ('start_timeline', models.DateTimeField()),
                ('end_timeline', models.DateTimeField()),
                ('completed', models.BooleanField()),
                ('poc_name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='backend.person')),
                ('team_name', models.ForeignKey(db_column='team_name', on_delete=django.db.models.deletion.CASCADE, to='backend.teams')),
            ],
        ),
    ]
