# Generated by Django 3.1.2 on 2020-11-08 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('team_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('year', models.CharField(max_length=100)),
                ('profile_pic', models.BinaryField()),
                ('about_me', models.CharField(max_length=300)),
                ('skills', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('counter', models.IntegerField(default=5)),
                ('start_timeline', models.DateTimeField()),
                ('end_timeline', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('poc_username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='backend.person')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=1000)),
                ('team_leader', models.CharField(max_length=100)),
                ('team_info', models.CharField(max_length=100000)),
                ('team_progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('team_picture', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.CharField(max_length=600)),
                ('timestamp', models.DateTimeField()),
                ('announcement_user', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='backend.credentials')),
                ('team_name', models.ForeignKey(db_column='team_name', on_delete=django.db.models.deletion.CASCADE, to='backend.teams')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=75)),
                ('project_name', models.ForeignKey(db_column='project_name', on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team_name',
            field=models.ForeignKey(db_column='team_name', on_delete=django.db.models.deletion.CASCADE, to='backend.teams'),
        ),
    ]
